server:
  port: 8081


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://fss.com:3306/wx_db
    username: z
    password: Q

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: zzzjoy.dao


#测试平台
wx:
  app-id: wx7c2
  secret: d87271c
  token: w
  limitTimes: 20
  frozenTime: 3

jwc:
  aesKey: XASEqd212fq1
  jwc-service: http:///main_handle
